# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-28 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0003_auto_20180806_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
