# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-25 16:49
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envoy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326, verbose_name='longitude/latitude'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('pending', "Pending - We've accepted the delivery and will be assigning it to a courier"), ('pick_up', 'Pick Up - Courier is assigned and is en route to pick up the items'), ('almost_pickup', 'Almost Pickup - The driver is close to the pickup point'), ('waiting_at_pickup', 'Waiting At Pickup The driver is waiting at the pickup point'), ('pickup_complete', 'Picking Complete - Courier has picked up the items'), ('dropoff', 'Dropoff - Courier is moving towards the dropoff'), ('almost_dropoff', 'Almost Dropoff - The driver is close to the delivery point'), ('waiting_at_dropoff', 'Waiting At Dropoff - The driver is waiting at the delivery point'), ('cancelled', "Cancelled -  Items won't be delivered. Deliveries are either canceled by the customer or by our customer service team"), ('delivered', 'Delivered - The package has been delivered successfully'), ('returned', 'Returned - The delivery was returned'), ('scheduled', 'Scheduled - The job has been scheduled. It will start later'), ('expired', "Expired - job has expired. No driver accepted the job. It didn't cost any money")], default='pending', max_length=32),
        ),
    ]
