# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-20 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envoy', '0004_pickup_pickup_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addressbook.Contact'),
        ),
    ]
