# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-04 00:16
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields
import sendhut.db


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.CharField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('metadata', jsonfield.fields.JSONField(blank=True, max_length=360, null=True)),
                ('first_name', models.CharField(max_length=152)),
                ('last_name', models.CharField(max_length=152)),
                ('email', models.EmailField(max_length=42, unique=True)),
                ('phone', models.CharField(max_length=30, unique=True)),
                ('address', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'partner',
            },
            bases=(models.Model, sendhut.db.UpdateMixin),
        ),
    ]
