# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-25 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='address',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
    ]
