# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-25 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields
import sendhut.db


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_auto_20180625_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.CharField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('metadata', jsonfield.fields.JSONField(blank=True, max_length=360, null=True)),
                ('name', models.CharField(max_length=100)),
                ('business_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('has_fleets', models.BooleanField(default=False)),
                ('delivery_volume', models.CharField(blank=True, choices=[('kicking-off', '0-50 deliveries per month'), ('growing', '0-100 deliveries per month'), ('expanding', '100-200 deliveries per month'), ('scaling', '300+ deliveries per month')], max_length=50, null=True)),
            ],
            options={
                'db_table': 'merchant',
            },
            bases=(models.Model, sendhut.db.UpdateMixin),
        ),
    ]
